### ISSUE TITLE
I am using visual studio 2015 enterprice and getting error (Errpr : "node" is ambigious")?

### ISSUE THREAD

**Issue by arsalan993** [HsiehYiChia/canny_text#1]
Debugger takes me to ER.h
struct Node
{
	Node(ER *v, const int i) : vertex(v), index(i){};
	ER* vertex;
	int index;
	vector<Node> adj_list;
	vector<double> edge_prob;
};

typedef vector < Node >  Graph;

In Type def vector < Node > Graph , Node is ambiguous

**Comment by HsiehYiChia** [comment]
Hi Arsalan,

The definition of Graph should be typedef vector<Node> Graph;
It seems that your code could be wrong, it should be compilable after you
git clone and config some environment variables.

[image: 內置圖片 1]


Best regards,
Yichia

2017-11-22 19:04 GMT+08:00 Arsalan Ahmed <notifications@github.com>:

**Comment by HsiehYiChia** [comment]
The definition of Graph should be typedef vector<Node> Graph;
It seems that your code could be wrong, it should be compilable after you git clone and config some environment variables.

**Comment by arsalan993** [comment]
Sir, I just edited my first comment actually i didnt cause any changes to your code ,  it gitclone as it is ..  linked OpenCV to it and when i run it i get 8 errors and all 8 errors are related to This "Node" struct. 
Type def is one of them ..  where ever in code you call "Node" i get this error.. 
So over all 8 errors because of Node

**Comment by arsalan993** [comment]
can u upload .exe file

**Comment by arsalan993** [comment]
Who ever get this error just Change the word "Node"  to "Node1" ,  because Word "Node" is clashing with pre-existing "Node"
