### ISSUE TITLE
Now i am getting this error after running the .exe file

### ISSUE THREAD

**Issue by arsalan993** [HsiehYiChia/canny_text#2]
.\canny_text.exe -icdar
Error: the input file is not opened!!
Error: the input file is not opened!!
Error: the Transition Probability Table file is not opened!!

Btw i also tried to open up an image but same error

**Comment by HsiehYiChia** [comment]
Try to put the `dictionay/` or `dictionary/tp_table.txt` in the same directory with `.exe`.
Sorry for my terrible readme file and SW dependency, I should make sure it is able to run when you clone it.
In fact, I stopped to update the project and my environment is not available now, therefore I can't update it now.
Maybe I'll in the future when I got spare time, I mean maybe :P

**Comment by arsalan993** [comment]
So i ended up copying all data from /x64/release folder to main directory and it worked like charm

**Comment by arsalan993** [comment]
Keep in touch i might be needing more help ,

**Comment by arsalan993** [comment]
Is this algorithm heavily dependent on Font type.. how can i add more fonts..  does it requires training or not. 
How much is the accuracy and on which relevant font size in an image it works fine

**Comment by HsiehYiChia** [comment]
1. Yes, the OCR model is based on edge feature, and therefore depends on font.  
2. To add font, you need to put every single letter in `ocr_classifier/FONTNAME/`, arrange them by font face and case. You can refer to `ocr_classifier/Calibri/Normal` to see the file layout. Then add font name to `font_name` in `ocr_classifier/get_ocr_data.py`. The script will do all the jobs and train model by `libsvm`, so make sure to put `libsvm` in `C:\`. Unfortunately, the script also need a `.exe` which I didn't not commit it and has lost, so **I don't think you can add new font.......**
3. The accuracy for end-to-end detection on ICDAR 2013 is roughly 70% with fine tune.  As for end-to-end recognition, I didn't test for it, but ICDAR 2013 winner is roughly 40%.
4. This algorithm works best with san-serif font.
5. Currently, `Deep Learning` is dominating this field, end-to-end recognition accuracy is higher than 90%, maybe you should try it. [Click me](http://rrc.cvc.uab.es/?ch=2&com=evaluation&task=4) to see ICDAR 2017 result
