### ISSUE TITLE
What does it mean to be “strong” and “weak”?

### ISSUE THREAD

**Issue by Sincky** [HsiehYiChia/canny_text#3]
I know it uses the machine classifier to judge non-text.
But i didn't know what does it mean to be “strong” and “weak”?
What are the "strong" and "weak" classifying based on?
I want to learn it and make it better to classify。

My English is no well，maybe you can't easily to read。
Hope to get your reply.

//Chinese 中文
strong和weak分类器是根据什么来判定的？
我想去深入了解一下并把它改进改进。

**Comment by HsiehYiChia** [comment]
The text classification system consist of 2 classifiers. All the detected ERs will go through strong classifier, and classified as strong-text and non-strong-text. Non-strong-text candidates will then go through weak classifier, and classified as weak-text and non-text.

![image](https://user-images.githubusercontent.com/13434801/38138848-6eff8cb4-345f-11e8-80df-7e3032fe77b9.png)

Strong text classifier has higher precision but lower recall, and vice versa. Recall and precision is a trade-off. The 2-stage classifier aim to provide better recall and precision than single classifier. You can refer to "Canny Text Detector: Fast and Robust Scene Text Localization Algorithm", which this algorithm is based on.
![image](https://user-images.githubusercontent.com/13434801/38138881-94d99eca-345f-11e8-9955-87dc1431c26d.png)

Your English is good enough to deliver your question, btw :D

**Comment by Sincky** [comment]
Thank you.You explained very clearly. :D
