### ISSUE TITLE
I get this error when executing it via VisualStudio2015

### ISSUE THREAD

**Issue by poetgeorge** [HsiehYiChia/canny_text#4]
The exe file can be compiled and executed but didnot show anything in the window,after some seconds I got this: Microsoft C++ Exception: std::length_error .

**Comment by HsiehYiChia** [comment]
I have no idea how that happened. Could you elaborate more about the issue?

**Comment by poetgeorge** [comment]
At the beginning , the .exe file cannot be compiled,so according to the errors I changed "Node" to "myNode",and deleted something like "<<<<<<HEAD". Then I began debugging,the .exe file can be compiled and executed,but showed a black window,then I got error"Microsoft C++ Exception: std::length_error" and the program interrupted.

**Comment by HsiehYiChia** [comment]
1. I didn't notice that there were some merge conflict, so I fix this.
2. Fix Node ambiguous problem by renaming `struct Node`  

I still don't have a clue how `std::length_error` occurs, but I hope this could help. If it's still not working for you, plz let me know.

**Comment by poetgeorge** [comment]
SUCCESS! I guess that the error is from the node ambiguous problem.
