### ISSUE TITLE
how can I train with my own data

### ISSUE THREAD

**Issue by queshuren** [HsiehYiChia/canny_text#5]
Hi, You have done  a wonderful job. Can you tell me how to train with my own data? Thanks!

**Comment by HsiehYiChia** [comment]
Hi there,
All training related functions are available in utils.cpp, but some of them
could need some modifications to work.(sorry for my bad code maintenance,
maybe I'll fix this in some day :p)
You can also refer to main.cpp, in there I comment out some of the
functions I used to train data.

queshuren <notifications@github.com> 於 2018年6月18日 週一 上午12:42 寫道：
